source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ChiefTags_Example', :exclusive => true do
  pod "ChiefTags", :path => "../"
end

target 'ChiefTags_Tests', :exclusive => true do
  pod "ChiefTags", :path => "../"

  pod 'FBSnapshotTestCase'
end
